dist: xenial

sudo: required

group: travis_lts

language: python

matrix:
  include:
    - env:
        - BUILD_NAME=UBUNTU_BIONIC_3_7
        - GYM_DARTPY_PYTHON_MAJOR_VERSION="3"
        - DOCKER_FILE="ubuntu-disco"
      services: docker

    - env:
        - BUILD_NAME=UBUNTU_BIONIC_3_7
        - GYM_DARTPY_PYTHON_MAJOR_VERSION="3"
        - DOCKER_FILE="ubuntu-eoan"
      services: docker

before_install:
  - if [ -n "$DOCKER_FILE" ]; then
      docker build -t "$DOCKER_FILE" -f ".ci/docker/$DOCKER_FILE" .;
      docker run -itd -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR --env-file .ci/docker/env.list --name my-docker "$DOCKER_FILE";
    fi

install:
  - if [ -n "$DOCKER_FILE" ]; then
      docker exec my-docker /bin/sh -c "cd $TRAVIS_BUILD_DIR && ./.ci/install.sh";
    else
      '.ci/install.sh';
    fi

script:
  - if [ -n "$DOCKER_FILE" ]; then
      docker exec my-docker /bin/sh -c "cd $TRAVIS_BUILD_DIR && ./.ci/script.sh";
    else
      '.ci/script.sh';
    fi